# configuration parsing starts here
defaults:
  - experiment: exp_planning # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: maze2d_umaze # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: rff_planning # algorithm yaml file name in configurations/algorithm folder [fixme]
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: mycoalchen # wandb account name / organization name [fixme]
  project: diffusion-forcing # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: online # set wandb logging to online, offline or dryrun

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wanmdb run id containing checkpoint or a path to a checkpoint file

# FOR SHAPE DEBUGGING
experiment:
  # training:
    # max_epochs: 2
    # limit_batch: 1
  validation:
    # batch_size: 2
    # limit_batch: 1
    val_every_n_epoch: 4
# algorithm:
  # warmup_steps: 0
  # rf:
  #   architecture:
  #     network_size: 16
  #     num_layers: 3
  #     attn_heads: 2
  #     dim_feedforward: 32
